[Exposed=Window]
interface MediaStream : EventTarget {
  
  //constructor();
  constructor(optional any stream = null);
  //constructor(sequence<MediaStreamTrack> tracks);
  
  //readonly attribute DOMString id;
  //readonly attribute boolean active;
  
  //sequence<MediaStreamTrack> getAudioTracks();
  //sequence<MediaStreamTrack> getVideoTracks();
  //sequence<MediaStreamTrack> getTracks();
  //MediaStreamTrack? getTrackById(DOMString trackId);
  //undefined addTrack(MediaStreamTrack track);
  //undefined removeTrack(MediaStreamTrack track);
  //MediaStream clone();
  
  //attribute EventHandler onaddtrack;
  //attribute EventHandler onremovetrack;
};

