[Exposed=Window]
interface MediaStreamTrack : EventTarget {
  
  attribute boolean enabled;
  readonly attribute boolean muted;
  readonly attribute DOMString kind;
  readonly attribute DOMString id;
  readonly attribute DOMString label;
  readonly attribute MediaStreamTrackState readyState;

  attribute EventHandler onmute;
  attribute EventHandler onunmute;
  attribute EventHandler onended;
  
  MediaStreamTrack clone();
  undefined stop();
  MediaTrackCapabilities getCapabilities();
  MediaTrackConstraints getConstraints();
  MediaTrackSettings getSettings();
  Promise<undefined> applyConstraints(optional MediaTrackConstraints constraints = {});
};